# Generated by Django 5.2.10 on 2026-01-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_returnrequest_refund_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('applied_for_return', 'Applied for Return'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
