# Generated by Django 5.2.9 on 2026-01-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_returnrequest_refund_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='defect_image',
            field=models.ImageField(blank=True, help_text='Image of the defect or issue', null=True, upload_to='return_images/'),
        ),
    ]
